config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :groups, except: %i(destroy show) do
    resources :messages, only: %i(index create)
  end
  resources :users, only: %i(index edit update)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users, through: :group_users
  has_many :group_users
  has_many :messages

  validates :name, presence: true

  def latest_message
    latest_messages = messages.last
    if latest_messages.present?
      latest_messages.message
    else
      "投稿はありません。"
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :message, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups, through: :group_users
  has_many :group_users
  has_many :messages

  validates :name, presence: true
  validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :set_group, only: %i(edit update)

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_messages_path(@group), notice: "グループが作成されました"
    else
      render :new, alert: "グループが作成できませんでした"
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to root_path, notice: "グループが更新されました"
    else
      render :edit, alert: "グループが更新されませんでした"
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { user_ids: [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group, only: %i(index create)

  def index
    @groups = current_user.groups
    @messages = @group.messages.includes(:user)
    @message = Message.new
    respond_to do |format|
      format.html
      format.json { @new_message = @messages.where('id > ?', params[:id])  }
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group) }
        format.json
      end
    else
      flash.now[:alert] = "メッセージを入力してください"
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:message).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}").where.not(name: params[:name])
    respond_to do |format|
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path, notice: "ユーザー情報の更新に成功しました"
    else
      render :edit, alert: "ユーザー情報の更新に失敗しました"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def simple_time(time)
    time.strftime("%Y-%m-%d　%H:%M　")
  end
end

app/views/groups/_form.html.haml
= form_for group do |f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "グループ名", class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field :name, placeholder: "グループ名を入力してください", id: "chat_group_name", class: "chat-group-form__input"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "チャットメンバーを追加" ,class: "chat-group-form__label", for: "chat_group_チャットメンバーを追加"
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", type: "text", for: "chat_group_チャットメンバーを追加"}
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "チャットメンバー", class: "chat-group-form__label"
    .chat-group-form__field--right
      #chat-group-users
        - group.users.reverse_each do |user|
          #chat-group-user-22.chat-group-user.clearfix
            = f.hidden_field :user_id, name: "chat-group[user_ids][]", type: "hidden", value: user.id
            %p.chat-group-user__name= user.name
            - if current_user.id != user.id
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "Save", class: "chat-group-form__action-btn"

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  #edit_chat_group_22.edit_chat_group
  = render partial: "form", locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render "layouts/sidebar"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  #new_chat_group.new_chat_group
  = render partial: "form", locals: { group: @group }

app/views/layouts/_flash.html.haml
.flash
  - flash.each do |key, value|
    = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/_sidebar.html.haml
.side-bar
  .header
    %h3.header__name
      = current_user.name
    %ul.header__lists
      %li.list
        = link_to edit_user_path(current_user) do
          = fa_icon "edit", class: "icon"
      %li.list
        = link_to new_group_path do
          = fa_icon "cog", class: "icon"
  .groups
    - @groups.each do |group|
      = link_to group_messages_path(group), class: "group__link" do
        .group{ "id": "#{group.id}" }
          .group__name
            = group.name
          .group__message
            = group.latest_message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace2
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "layouts/flash"
    = yield

app/views/messages/_message.html.haml
.message-content{"data-id": "#{message.id}"}
  .upper-message
    .upper-message__user-name
      = message.user.name
    .upper-message__date
      = simple_time(message[:created_at])
  .lower-message
    %p.lower-message__content
      = message.message
    = image_tag message.image.url if message.image.url.present?

app/views/messages/index.html.haml
.wrapper
  = render "layouts/sidebar"
  .chat
    .header
      .left-header
        .left-header__title
          = @group.name
        %ul.left-header__members
          Member :
          = @group.users.pluck(:name).join(',')
      .right-header
        = link_to "Edit", edit_group_path(@group), class: "right-header__btn"
    #js-messages.messages
      .message
        = render @messages

    .form
      = form_for [@group,@message], id: "new_message", class: "js-form" do |f|
        = f.text_field :message, placeholder: "type a message", id: "message_content", class: "form__message js-content"
        .form__mask
          = f.label :image, class: "form__mask__image" do
            = f.file_field :image, class: "hidden"
            %i.fa.fa-picture-o
        = f.submit "send", class: "form__submit"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'